### ISSUE TITLE
Добавить click listener в блок

### ISSUE THREAD

**Issue by NikitaZhdanov** [mfelements/mfelements.github.io#3]
Чтобы иметь возможность вызывать какое-то действие, при нажатии на блок (например переход на другую страницу), просьба добавить click listener в блок.

**Comment by KaMeHb-UA** [comment]
Для вызова действий предназначены кнопки, клик же по блоку может дискредитировать UX. Не уверен, что клик по блоку должен отслеживаться впринципе, это даже не совпадает с текущим концептом дизайна
